# -----------------------------------------------#
# mona.py configuration file                    #
# Corelan Consulting bv - https://www.corelan.be          #
# -----------------------------------------------#
workingfolder= c:\logs\%p
